library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -optc-O3
  - -fasm
  cpp-options:
  - -DNDEBUG
  - -O3

copyright: 2019 Mesabloo

dependencies:
- text
- base >= 4.7 && < 5
- megaparsec >7
- parser-combinators
- ansi-terminal
- wl-pprint
- containers
- mtl
- transformers
- unordered-containers
- directory
- haskeline
- MissingH
- multimap
- these <= 0.7.6
- criterion-measurement
- bytestring
- vector
- extra
- ghc
- composition
- keys
- hashable
- deepseq
- QuickCheck
- optparse-applicative
- filepath
- insert-ordered-containers
# - JellyVM
- invariant
- conf
- lens

name: Blob
version: 0.1.0.0
extra-source-files:
- README.md
author: Mesabloo
github: mesabloo/Blob
license: GPL-3.0

executables:
  Blob-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wextra
    - -Wno-unused-do-bind
    - -Wno-name-shadowing
    - -O2
    - -optc-O3
    - -fasm
    # - -prof
    # - -fprof-auto
    cpp-options:
    - -DNDEBUG
    - -O3
    dependencies:
    - Blob

description: Please see the README on GitHub at <https://github.com/mesabloo/Blob#readme>
