library:
  source-dirs: src

when:
- condition: flag(debug)
  cpp-options:
  - -DDEBUGGING
- condition: flag(profile)
  ghc-options:
  - -prof
  - -auto-all
  - -with-rtsopts=-p,-s
- condition: flag(dynamic)
  ghc-options:
  - -dynamic

ghc-options:
- -Wall
- -Wno-unused-do-bind
- -Wno-orphans
- -Wno-name-shadowing
- -Wno-unused-matches
- -O2
- -optc-Os

author: Ghilain Bergeron (Mesabloo)
github: mesabloo/nihil
license: BSD3
copyright: 2019 Ghilain Bergeron (Mesabloo)
description: Please see the README on GitHub at <https://github.com/mesabloo/nihil#readme>

dependencies:
- base
- megaparsec
- mtl
- lens
- ansi-wl-pprint
- text
- containers
- free
- comonad
- semialign
- these
- insert-ordered-containers
- hashable

# - containers
# - MissingH
# - these <= 0.7.6
# - criterion-measurement
# - bytestring
# - extra
# - keys
#
#

name: nihil
version: 0.1.0.0
extra-source-files:
- README.md
# .hs-boot files
- src/**/*.hs-boot

executables:
  # Nihili:
  #   source-dirs: app
  #   main: Main.hs
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - nihil
    # - optparse-applicative
    # - process
    # - conf
    # - directory
    # - haskeline
    # - ansi-wl-pprint
    # - filepath
  nihilin:
    source-dirs: app/nihilin
    main:        Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optc-O2
    dependencies:
    - nihil

flags:
  debug:
    description: "Enable/disable compiler debugging features."
    manual: true
    default: false
  profile:
    description: "Enable/disable compiler profiling."
    manual: true
    default: false
  dynamic:
    description: "Dynamically link libraries"
    manual: true
    default: false

tests:
  compiler:
    main:        Spec.hs
    source-dirs: tests/compiler
    ghc-options:
    - -O0
    - -optc-O0
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nihil
    - hspec
  utils:
    main:        Spec.hs
    source-dirs: tests/utils
    ghc-options:
    - -O0
    - -optc-O0
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nihil
    - hspec
