library:
  source-dirs: src

when:
- condition: flag(debug)
  cpp-options:
  - -DDEBUGGING

ghc-options:
- -Wall
- -Wno-unused-do-bind
- -Wno-orphans
- -Wno-name-shadowing
- -Wno-unused-matches
- -O2
- -optc-O3

copyright: 2019 Mesabloo
description: Please see the README on GitHub at <https://github.com/mesabloo/nihil#readme>

dependencies:
- base
- megaparsec
- mtl
- lens
- ansi-wl-pprint
- text
- containers
- free
- comonad
- semialign
- these
- insert-ordered-containers
- hashable

# - containers
# - MissingH
# - these <= 0.7.6
# - criterion-measurement
# - bytestring
# - extra
# - keys
#
#

name: nihil
version: 0.1.0.0
extra-source-files:
- README.md
# .hs-boot files
- src/Nihil/Syntax/Concrete/Parser/Expression.hs-boot
- src/Nihil/Syntax/Concrete/Parser/Pattern.hs-boot
- src/Nihil/Syntax/Concrete/Parser/Type.hs-boot
- src/Nihil/Syntax/Abstract/Desugarer/Expression.hs-boot

author: Mesabloo
github: mesabloo/nihil
license: GPL-3.0

executables:
  # Nihili:
  #   source-dirs: app
  #   main: Main.hs
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - nihil
    # - optparse-applicative
    # - process
    # - conf
    # - directory
    # - haskeline
    # - ansi-wl-pprint
    # - filepath
  nihilin:
    source-dirs: app/nihilin
    main:        Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nihil

flags:
  debug:
    description: "Enable/disable compiler debugging features."
    manual: true
    default: false

tests:
  lexer:
    main:        Main.hs
    source-dirs: tests/Lexer
    dependencies:
    - nihil
    - hspec