library:
  source-dirs: src

when:
- condition: flag(profile)
  ghc-options:
  - -prof
  - -auto-all
  - -with-rtsopts=-p,-s

ghc-options:
- -Wall
- -Wno-unused-do-bind
- -Wno-orphans
- -Wno-name-shadowing
- -Wno-unused-matches
- -O2
- -optc-O3

author: Ghilain Bergeron (Mesabloo)
github: mesabloo/nihil
license: BSD3
copyright: 2019 Ghilain Bergeron (Mesabloo)
description: Please see the README on GitHub at <https://github.com/mesabloo/nihil#readme>

dependencies:
- base
- gnc-utils
- gnc-core
- gnc-parser
- gnc-typechecker
- gnc-runtime
- gnc-pretty

name: gnc
version: 0.1.0.0
extra-source-files:
- README.md

executables:
  nihilin:
    source-dirs: app/nihilin
    main:        Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-type-defaults
    dependencies:
    - gnc
    - containers
    - lens
    - megaparsec
    - mtl
    - ansi-wl-pprint
    - text

flags:
  profile:
    description: "Enable/disable compiler profiling."
    manual: true
    default: false

tests:
  compiler:
    main:        Spec.hs
    source-dirs: tests/compiler
    ghc-options:
    - -O0
    - -optc-O0
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gnc
    - hspec
  utils:
    main:        Spec.hs
    source-dirs: tests/utils
    ghc-options:
    - -O0
    - -optc-O0
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gnc
    - hspec
