library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -optc-O3
  - -fasm
  - -Wno-unused-do-bind
  - -Wno-orphans
  - -Wno-name-shadowing
  - -Wno-unused-matches
  cpp-options:
  - -DNDEBUG
  - -O3

copyright: 2019 Mesabloo

dependencies:
- text
- base >= 4.7 && < 5
- megaparsec >7
- ansi-wl-pprint
- containers
- mtl
- MissingH
- these <= 0.7.6
- criterion-measurement
- bytestring
- extra
- keys
- hashable
- insert-ordered-containers
- lens
- binary
- vector
- unix
- template-haskell

name: Blob
version: 0.1.0.0
extra-source-files:
- README.md
author: Mesabloo
github: mesabloo/Blob
license: GPL-3.0

executables:
  iBlob:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -optc-O3
    - -fasm
    - -Wno-unused-do-bind
    - -Wno-orphans
    - -Wno-name-shadowing
    - -Wno-unused-matches
    # - -prof
    # - -fprof-auto
    cpp-options:
    - -DNDEBUG
    - -O3
    dependencies:
    - Blob
    - optparse-applicative
    - process
    - conf
    - directory
    - haskeline
    - ansi-wl-pprint
    - filepath

description: Please see the README on GitHub at <https://github.com/mesabloo/Blob#readme>

tests:
  lexer:
    main:        Main.hs
    source-dirs: tests/Lexer
    dependencies:
    - Blob
    - hspec
  parser:
    main:        Main.hs
    source-dirs: tests/Parser
    dependencies:
    - Blob
    - hspec
  jit:
    main:        Main.hs
    source-dirs: tests/JIT
    ghc-options:
    - -g
    # - -dcore-lint
    # - -debug
    # - -ddump-stg
    # - -ddump-simpl
    # - -ddump-cmm
    # - -dppr-debug
    # - -ddump-to-file
    dependencies:
    - Blob