library:
  source-dirs: src
  ghc-options:
  - -Wall
copyright: 2019 Mesabloo
dependencies:
- text
- base >= 4.7 && < 5
- megaparsec >7
- parser-combinators
- ansi-terminal
- wl-pprint
- containers
- mtl
- transformers
- unordered-containers
- directory
- haskeline
- MissingH
- multimap
- these
- criterion-measurement
- bytestring
name: Blob
version: 0.1.0.0
extra-source-files:
- README.md
author: Mesabloo
github: mesabloo/Blob
license: GPL-3.0
executables:
  Blob-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - Blob
description: Please see the README on GitHub at <https://github.com/mesabloo/Blob#readme>
